<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>OECD Regional Outlook 2023 - Country Profiles - Belgium</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tl2-can.html" rel="next">
<link href="./tl3-aut.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tl3-bel.html"><span class="chapter-title">Belgium</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">OECD Regional Outlook 2023 - Country Profiles</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Australia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-aut.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Austria</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-bel.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Belgium</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl2-can.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Canada</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl2-chl.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chile</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-col.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Colombia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-cri.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Costa Rica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-cze.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Czech Republic</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-dnk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Denmark</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-est.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estonia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-fin.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Finland</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-fra.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">France</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-deu.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Germany</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-grc.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Greece</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-hun.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hungary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-isl.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iceland</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-irl.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ireland</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-isr.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Israel</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-ita.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Italy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-jpn.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Japan</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-kor.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Korea</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-lva.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Latvia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-ltu.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lithuania</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-lux.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Luxembourg</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl2-mex.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mexico</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-nld.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Netherlands</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-nzl.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">New Zealand</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-nor.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Norway</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-pol.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Poland</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-prt.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Portugal</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-svk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Slovak Republic</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-svn.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Slovenia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-esp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-swe.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sweden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-che.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Switzerland</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-tur.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Turkey</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl3-gbr.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">United Kingdom</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tl0-usa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">United States</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#regional-inequality-trends" id="toc-regional-inequality-trends" class="nav-link" data-scroll-target="#regional-inequality-trends">Regional inequality trends</a></li>
  <li><a href="#recent-policy-developments" id="toc-recent-policy-developments" class="nav-link" data-scroll-target="#recent-policy-developments">Recent policy developments</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Belgium</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>


<table border="1" style="width:75%;margin-left:auto;margin-right:auto;">
<tbody><tr>
<th colspan="2" style="background:#fff9e6; padding:10px;font-size:9.0pt;" valign="center">
OECD Regional Outlook
</th>
</tr>
<tr>
<td>
<img style="padding:10px;" src="RO2023_cover.jpg" alt="OECD Regional Outlook 2023" height="200">
</td>
<td>
<p style="padding:10px;font-size:9.0pt;">
The OECD <a href="https://www.oecd-ilibrary.org/urban-rural-and-regional-development/oecd-regional-outlook_2dafc8cf-en" target="_blank"><i style="color:#0d6efd">Regional Outlook</i></a> reviews recent trends, policy developments, and prospects across OECD regions, including the underlying causes driving regional inequalities in performance and well-being. The report offers evidence, guidance and policy recommendations on how to improve competitiveness and productivity, promote inclusive growth, accelerate the net-zero transition and raise well-being standards through effective regional development policy and multi-level governance.
</p>
</td>
</tr>

</tbody></table>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header header">
<th data-quarto-table-cell-role="th">Population and territory</th>
<th data-quarto-table-cell-role="th">11.681.087 (23 January 2023) - 30 530 km2</th>
</tr>
</thead>
<tbody>
<tr class="odd odd">
<td>Administrative structure <em></em></td>
<td>Federal</td>
</tr>
<tr class="even even">
<td>Regional or state-level governments <em></em></td>
<td><p>6 federated entities: 3 regions and 3 communities</p>
<ul>
<li><p>The Flemish Region (<em>Vlaams Gewest)</em> represents 44% of the Belgian territory and 57.9% of its population</p></li>
<li><p>The Walloon Region (Région Wallonne) accounts for 55% of the area and 31.4% of the population.</p></li>
<li><p>The Brussels Capital Region (Région de Bruxelles-Capitale, <em>Brussels Hoofdstedelijk Gewest</em>) accounted for 0.53% of Belgian territory but 10,7 % of the total population in 2023.</p></li>
</ul>
<p>The three communities cut across the regions. In particular, the Flemish Community comprises all the inhabitants of Flanders and Brussels-based Flemings. The French Community comprises all the residents of Wallonia as well as Brussels-based French-speaking inhabitants. The German-speaking Community comprises all the inhabitants of the nine German-speaking municipalities in the east of Belgium.</p></td>
</tr>
<tr class="odd odd">
<td>Intermediate-level governments <em></em></td>
<td><p>10 provinces</p>
<p>The intermediary layer of government includes 10 provinces, with five provinces in the Flemish region and five others in the Walloon region. Regions are very diverse in terms of population, size and land mass. The Brussels Capital Region directly exercises provincial responsibilities. The provincial government consists of three main institutions: (i) the provincial council which is the deliberative body elected every six years by direct universal suffrage and chaired by a president (elected among its members); (ii) the permanent deputation (in Flanders) or provincial college (in Wallonia), which is the executive body (its representatives are appointed by the provincial council among their own members); and (iii) the Governor, who is appointed by the regional government. Provinces are themselves sub-divided into administrative districts.</p></td>
</tr>
<tr class="even even">
<td>Municipal-level governments <em></em></td>
<td><p>581 communes</p>
<p>The municipal tier of government comprises 581 municipalities, which have been governed by legislation, gradually devolved to the regions since 1980. The deliberative body is the municipal council whose representatives are elected every six years by direct universal suffrage. The executive body is the college of Mayor and aldermen. Aldermen are elected by the municipal council, while the Mayor is nominated according to different rules depending on the region.</p>
<p>The number of municipalities has been stable for around 45 years, following a process of compulsory mergers between 1965 and 1983. In particular, the 1975 royal decree reduced the number of municipalities from 2 359 to 596. In 2020, the Flemish Region had 300 municipalities (from 308 following mergers in 2019), while the Walloon region has 262 and Brussels-capital 19. In its 2019 regional policy statement, the Walloon government announced its willingness to encourage municipal mergers on a voluntary basis both by financial and regulatory incentives, as well as by administrative and technical support.</p>
<p>The policy of promoting voluntary mergers, is also being implemented in Flanders. The Flemish Coalition Agreement 2019-2024 opts for voluntary mergers because the local governments themselves must be convinced of the need to strengthen their administrative power. That is why the Flemish Government stimulates as many municipalities as possible to merge. It supports the local councils that take the decision and guides and helps them in its implementation by financial and regulatory incentives, as well as by administrative and technical support.</p>
<p>The average municipal size in Belgium is almost twice the OECD average municipal size (around 10 250 inhabitants). There are very few small municipalities (1% of less than 2 000 inhabitants) as the majority (72%) have below 20 000 inhabitants.</p></td>
</tr>
<tr class="odd odd">
<td>Share of subnational government in total expenditure/revenues (2021)</td>
<td><p>49.9% of total expenditure</p>
<p>51.9% of total revenues</p>
<p>[Source: <a href="https://stats.oecd.org/Index.aspx?DataSetCode=SNGF">Subnational governments in OECD countries: key data, 2023 edition</a>]</p>
<p>Fiscal decentralisation, the devolution of revenue collection and expenditure execution responsibilities from the federal to the regions and the communities, has progressed in stages under six state reforms implemented over five decades.</p>
<p>With regards to the revenue side, Regions have several tax including registration duties on sales of real estate, inheritance and gift tax, an annual tax on vehicles and a property tax. Since the last constitutional reform, regions are able to raise surcharges of personal income tax.</p></td>
</tr>
<tr class="even even">
<td>Key regional development challenges</td>
<td><p><strong>Brussels-Capital region</strong></p>
<p>The Brussels Government has committed itself to an ambitious global policy aiming to meet the social, economic, and environmental challenges facing the region. Therefore, the various thematic measures and strategic objectives are integrated into a coherent political vision at the level of the Region which, benefitting from inputs of social partners and of civil society, aims to empower all Brussels inhabitants throughout their lives, through access to housing and to quality employment, accessible health care, a healthy and convivial living environment and nearby public and transport infrastructure. More broadly, the environmental issues as well as the challenges imposed by the climate emergency are answered with specific and collective responses, which are part of a long-term approach, in all sectors and in every area of regional competence. From this, some key challenges can be distinguished:</p>
<ul>
<li><p>Socio-spatial disparities: urban regeneration policies, inclusion policies and public housing policies</p></li>
<li><p>Sustainability, climate change, biodiversity and Economic transition: productive and circular city, city of proximity, climate-neutral city</p></li>
<li><p>Demographic patterns: development of new (social) housing, green spaces and public amenities according to the needs and the diversity of inhabitants</p></li>
<li><p>Finance: the Brussels-Capital Region faces substantial budget constraints as well as a large debt, due to a number of factors, including declining tax revenues and increasing expenditures on social services and infrastructure projects.</p></li>
<li><p>Governance: Decision making is highly complex + need for greater efficiency</p></li>
<li><p>Mobility: multimodality and multi-layer approaches</p></li>
</ul>
<p><strong>Flanders</strong></p>
<p>The Flemish Resilience Plan is an ambitious investment plan to ensure the transition to a sustainable and digital economy and to make Flanders a warm, inclusive society with people who are more employable on the labour market. The plan defines seven key focal points:</p>
<ul>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/making-the-economy-and-society-more-sustainable">Making the economy and society more sustainable</a> (Climate, sustainability, and innovation)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/investing-in-infrastructure">Investing in infrastructure</a> (The Government of Flanders is investing in infrastructure and major mobility works)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/transforming-flanders-digitally">Transforming Flanders digitally</a> (Digitalization to the maximum extent possible)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/investing-in-people-and-talents">Investing in people and talents</a> (Promoting lifelong learning and digitalization in education and on the labour market)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/strengthening-flanders-care-and-welfare-system">Strengthening Flanders’ care and welfare system</a> (Additional resources for care and welfare)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/managing-the-corona-crisis-and-brexit">Managing the corona crisis and Brexit</a> (Emerging from the corona crisis and Brexit)</p></li>
<li><p><a href="https://www.vlaanderen.be/en/authorities/flemish-resilience/making-government-more-efficient">Making government more efficient</a> (Less red tape and greater efficiency)</p></li>
</ul>
<p><strong>Wallonia</strong></p>
<ul>
<li><p>Carry-out a strong and sustainable economic and industrial policy</p></li>
<li><p>Strengthen independence and energy transition</p></li>
<li><p>Get out of precariousness</p></li>
<li><p>Strengthen training</p></li>
</ul></td>
</tr>
<tr class="odd odd">
<td>Objectives of regional policy</td>
<td><p>Each of the three regions is competent for its regional policy:</p>
<p><strong>Brussels-Capital Region</strong></p>
<p>During this legislature 2019-2023, the Brussels Government has committed itself to the following objectives:</p>
<ul>
<li>A region where everyone can live with respect and dignity:
<ul>
<li><p>Ensuring that everyone can live at a reasonable price and with public facilities nearby, strengthening the social integration of vulnerable people;</p></li>
<li><p>Ensuring access to stable and sustainable employment</p></li>
<li><p>Ensuring access to healthcare and addressing inequalities</p></li>
<li><p>Ensuring equal rights and combating discrimination effectively</p></li>
</ul></li>
<li>Economic and social development framed within an ecological transition model:
<ul>
<li><p>Economic innovation at the service of transition: developing an urban economy capable of ensuring prosperity, both by mobilising the strong points and promising sectors and by stimulating the local economy and innovation (circularity, etc.),</p></li>
<li><p>Promote multimodal travel by strengthening active modes of transport, public transport networks and modal rebalancing</p></li>
<li><p>The climate challenge: An integrated territorial development and environmental policy</p></li>
<li><p>An energy strategy that relies on the renovation of buildings and the production of renewable energy</p></li>
</ul></li>
<li><p>A region with a strong identity and an open view of the world, which strengthens its service to its citizens strengthened by striving for manageable institutions that are close to the people.</p></li>
</ul>
<p><strong>Flanders</strong></p>
<p>Flanders is bouncing back, partially thanks to <em>Flemish Resilience</em>. The Government of Flanders’ ambitious investment plan ensures the transition to a sustainable and digital economy. It makes Flanders a warm, inclusive society with people who are more employable on the labour market. Flemish Resilience makes Flanders resilient.</p>
<p>Despite the five COVID-19 waves and the crisis in Ukraine, the implementation of the Flemish Resilience plan is going largely as planned. 96% of the projects are on schedule; 92% of the initiated milestones have been achieved or are on schedule. Commitments have also risen substantially to 46.5% of the recovery funds or EUR 2 billion. Clear progress has been made again compared to the measurements from March, September, and December 2021.</p>
<p>The Flemish Government aims to achieve an 80% employment rate by 2030, in line with the targets in the European Pillar of Social Rights. In 2022, Flanders reached an employment rate of 76.7% for the 20-64 age group. The current Flemish labour market is characterized by a high labour market tightness with labour shortages in some sectors. To ease these shortages and to work towards the 2030 target of 80%, the Flemish Government and the Flemish social partners concluded a new employment agreement ‘Iedereen nodig, Iedereen mee’ in 2022.</p>
<p>The employment agreement consists of four pillars: results-oriented active labour market policies form the first pillar. The second pillar revolves around lifelong learning, upskilling and reskilling people to get the right skills for current and future jobs. The Flemish Government wants to reach a 60% rate for training participation by 2030. The third pillar is about ‘workable’ jobs, and improving the quality of work, to enable longer and more fulfilling careers. The fourth and last pillar is centred around economic migration and interregional mobility.</p>
<p>With an <strong>R&amp;D intensity</strong> in 2020 of 3.60% of GDP, Flanders has far exceeded the 3% R&amp;D standard. R&amp;D expenditure in Flanders is almost € 9,59 billion, which is 62% of Belgium’s total R&amp;D expenditure in 2019. Spreading R&amp;D across more sectors and business types remains a challenge for our region. With increasing R&amp;D resources, Flanders aims to advance to the top 5 innovative knowledge regions in Europe.</p>
<p><strong>Wallonia</strong></p>
<ul>
<li><p>Capitalise on the youth and talents of Wallonia</p></li>
<li><p>Ensure environmental sustainability</p></li>
<li><p>Boost economic development</p></li>
<li><p>Support well-being, solidarity and social inclusion</p></li>
<li><p>Guarantee innovative and participatory governance</p></li>
<li><p>Support the reconstruction and resilience of territories affected by the floods of July 2021</p></li>
</ul></td>
</tr>
<tr class="even even">
<td>Legal/institutional framework for regional policy</td>
<td><p>The 1831 Constitution established Belgium as a unitary parliamentary monarchy. A process of federalisation started in the 1970s to take into consideration linguistic, cultural and socio-economic specificities. Six constitutional reforms took place between 1970, 2001 and 2011, the latter taking effect since 2012-2014.</p>
<p>The country’s federal structure of government has gradually but significantly evolved over the past decades towards a greater devolution of decision-making power to the six federated entities, made up of three regions (the Flemish Region, the Walloon Region and the Brussels-Capital Region) and three communities (the Flemish Community, the French Community and the German-speaking community). The determining characteristic of a region is its geographical area while that of a community is its culture and language.</p>
<p>At the federal level, the legislative power is exercised by the Federal Parliament, composed of two assemblies: the Chamber of the Representatives and the Senate. Following the 6th State Reform, members of the Senate (the upper house which serves as a chamber of the communities and regions) are designated by the federated entities (50/60) or co-opted (10/60), and no longer elected (Art. 67 of the Constitution). Senators have no veto powers over federal legislation.</p>
<p>At the regional level, there are five legislatures, elected for a five-year term, and five governments, elected by the Parliament, which in turn elects a president: (i) the Flemish Parliament and Government (which represent both the region of Flanders and the Flemish community), (ii) the Walloon Parliament and Government, (iii) the French-speaking Community Parliament and Government (Fédération Wallonie-Bruxelles), (iv) the Brussels Region Parliament and Government and (v) the German-speaking Community Parliament and Government. The following can be said with regard to the exercise of the powers of the Flemish and French Communities in the Brussels Capital Region. The Flemish Community Council (Vlaamse Gemeenschapscommissie, VGC) takes care of the responsibilities of the Flemish Community in the Brussels Capital Region. The French Community Commission (COCOF) takes care of the responsibilities of the French Community in the Brussels Capital Region. The Common Community Council (COCOM) regulates and manages matters common to the two Communities in the Brussels Capital Region.</p>
<p>Belgian federalism severely limits the scope for governments to interfere in subnational levels of responsibilities. The distribution of responsibilities between the regions and communities and the federal level is subject to judicial control, exercised by the Constitutional Court of Belgium, which can annul legislative acts that contravene the division of powers, and by the Council of State, which has the same competence regarding administrative acts contravening the division of powers. The 6th state reform transferred additional responsibilities to regions and communities.</p>
<p><strong>Brussels-Capital Region</strong></p>
<ul>
<li><p>General Policy Statement of the Government of the Brussels-Capital Region 2019-2024</p></li>
<li><p>Recovery and redeployment plan to address the Covid-19 crisis</p></li>
</ul>
<p><strong>Wallonia</strong></p>
<p>Regional Policy Statement 2019-2024</p></td>
</tr>
<tr class="odd odd">
<td>Budget allocated to regional development (i.e., amount) and fiscal equalisation mechanisms between jurisdictions (if any)</td>
<td>The main financial transfer to the regions is the so-called federal personal income tax transfer. Regions with personal income tax yield per capita that are below the national average receive an equalisation transfer (the “National Solidarity Mechanism”) from the federal government. This aims to reduce the revenue gap between the regions and reduce the differences in public service provision. The solidarity mechanism was reformed under the 6<sup>th</sup> State Reform.</td>
</tr>
<tr class="even even">
<td>National regional development policy framework</td>
<td></td>
</tr>
<tr class="odd odd">
<td>Urban policy framework</td>
<td><p>Since the 6<sup>th</sup> State Reform, dating from 2011, the three regions – Flanders, Walloon Region and Brussels Capital Region – are responsible for their own urban policy. Each of the three regions determines its own urban policy autonomously. The regions consult with each other regularly and structurally in matters which need a nationally coordinated point of view, as is – for example, the case with the Urban Development Group (UDG) or the meetings of the Directors-General for Urban Matters (DGUM). As to urban policy, the federal level only has a limited role (mainly knowledge exchange).</p>
<p><strong>Brussels-Capital Region</strong></p>
<p>The main urban policy instruments in the Brussels-Capital Region are:</p>
<ul>
<li><p>Brussels Code for Spatial Planning (last change in 2018 and changes under evaluation): it is the main regulation organizing spatial and land-use planning: who does what, which tools, which procedures, which hierarchy of norm…</p></li>
</ul>
<ul>
<li>Strategic Plans (non-binding):
<ul>
<li><p>Regional Sustainable Development Plan adopted in 2018: the mid and long-term city vision</p></li>
<li><p>Municipal Development plans: idem for each municipality and must be in compliance with the regional vision.</p></li>
</ul></li>
<li>Regulatory Plans (binding):
<ul>
<li><p>Regional Land-use Plan (under revision): define the different uses of land at regional level (under regional direction)</p></li>
<li><p>Local land-use Plans: they detailed at the level of neighborhoods the Regional Land-use plan (under municipal direction)</p></li>
</ul></li>
<li>Strategic and Regulatory Plans (created in 2018):
<ul>
<li><p>Master Development Plans: instrument uses for big urban projects to define the strategic vision for the development or the area and to develop in parallel a regulatory part to make possible the implementation of the strategic vision and changes the different land—use or other urbanism related regulations.</p></li>
</ul></li>
<li>Urbanism Regulation: Defining the characteristics of the building (volume, aesthetic, height), the norm of habitability of housing, accessibility of building, development of public space, parking in public spaces…
<ul>
<li>Regional:
<ul>
<li><p>Regional urbanism Regulation (under revision): define generic characteristics of new / fully upgraded / renovated buildings</p></li>
<li><p>regional urbanism regulation for specific zones (same with appropriate rules for specific zones (built heritage…)</p></li>
</ul></li>
<li>Municipal (same tools at municipal level):
<ul>
<li><p>Municipal urbanism regulation</p></li>
<li><p>Municipal urbanism regulation for specific zones</p></li>
</ul></li>
</ul></li>
</ul>
<p><strong>Wallonia</strong></p>
<ul>
<li><p>Integrated Urban Development Strategy: <a href="https://europe.wallonie.be/sites/default/files/2022-03/WAPI_Strategie.pdf">https://europe.wallonie.be/sites/default/files/2022-03/WAPI_Strategie.pdf</a></p></li>
<li><p>Urban policy</p></li>
<li><p>Tools for urban renewal and revitalisation</p></li>
</ul></td>
</tr>
<tr class="even even">
<td>Rural policy framework</td>
<td><p>Both rural development and agriculture are regional competences. Part of the policy is determined by the European Union via the CAP: for the period 2023-2027, Belgium is the only member state that has received an exception to draw up 2 CAP plans (instead of 1 plan per member state): a Flemish CAP plan and a Walloon CAP plan.</p>
<p><strong>Flanders</strong></p>
<p>Rural development issues are also included in the Flemish CAP plan, e.g. LEADER.</p>
<p><strong>Wallonia</strong></p>
<ul>
<li><p>Walloon rural policy</p></li>
<li><p>Walloon Rural Development Programme</p></li>
</ul></td>
</tr>
<tr class="odd odd">
<td>Major regional policy tools (e.g., funds, plans, policy initiatives, institutional agreements, etc.)</td>
<td><p><strong>Brussels-Capital Region</strong></p>
<p>Within the Brussels Capital Region, there are several major regional policy tools, some of the most important are:</p>
<ul>
<li><p>Go4Brussels 2030</p></li>
<li><p>Shifting economy</p></li>
<li><p>Optiris</p></li>
<li><p>Good Move</p></li>
<li><p>Good Food</p></li>
<li><p>Small Business Act</p></li>
<li><p>Be Circular</p></li>
<li><p>Renolution</p></li>
<li><p>Regional Plan for Innovation</p></li>
</ul>
<p>One of the main economic polies is embedded in <em>Shifting Economy</em>, the regional strategy for the economic transition (<a href="https://shiftingeconomy.brussels/">https://shiftingeconomy.brussels/</a>). The strategy gathers more than 200 measures, aimed at helping the Brussels economic actors becoming exemplary on the social and environmental level. By 2030, no more public money will flow to economic actors who don't have exemplary business models. So that, by 2050, we reach a decarbonised and regenerative economy. Shifting Economy has been adopted on 31 March 2021 and is part of the reforms of the Belgian Recovery and Resilience Plan. The first evaluation of Shifting Economy is planned for 2024.</p>
<p>In addition, congestion is considered a problem by the region and the nuisances (environmental, noise, financial, etc.) it causes are taken seriously. The main strategies the region is putting in place are described in the <em>Good-Move regional mobility plan</em>. For example, the dynamic traffic flow management project aims to control this congestion in order to limit the various impacts. Mobility scenarios (modification of traffic lights, user information, implementation of diversions, etc.) have been developed and are activated for recurrent events (e.g. tunnel closure). Mobility managers" are active in our control center during peak hours or for incident management. They are able to remotely adapt traffic light regimes in real time to better control traffic and thus reduce congestion.</p>
<p>The <em>OPTIris</em> programme stands for "Optimising the Performance and Transition of Institutions". It aims to respond to the challenges the Region will face in the future through reforms that will also enable structural savings of €60 million a year within the perimeter of the regional entity.</p>
<p><strong>Flanders</strong></p>
<p>The Flemish Region is responsible for the general financing of cities and municipalities. In Flanders this concerns the Municipal Fund and a number of other endowments that are provided without conditions to the Flemish cities and municipalities (and their Public Centers for Social Welfare). In Flanders, this will amount to just over 4 billion euros (4,040,054,000) in 2022. In comparison, in 2021 the total revenue of the Flemish cities and municipalities amounted to 15,587,715,901 euros.</p>
<p>In addition to this general, condition-free basic funding, various parts of the Flemish Authority also provide various <u>specific, condition-related subsidies</u> to the cities and municipalities. In Flanders, these subsidies (both the number and the size) have increased in recent years, partly as a result of the policy option to intervene in the extra expenditure of Flemish cities and municipalities as a result of the Covid-19 crises.</p>
<p>The Flemish Authority is also responsible for determining the way in which the cities and municipalities draw up their <u>multiannual plan (and its annual adjustments), keep their accounts and draw up their annual accounts</u>. In Flanders, this system is called BBC – policy and management cycle. The Government of Flanders specifically supervises the (adapted) multi-year plans and annual accounts. The (adjusted) multi-annual plans must have a positive self-financing margin at the end of the planning period. The cities and municipalities are also obliged to digitally provide certain data of the policy reports to the Government of Flanders.</p>
<p><strong>Wallonia</strong></p>
<p>44 strategies and plans: <a href="https://developpementdurable.wallonie.be/sites/dd/files/2022-09/SWDD3_2022_CH2_strat%C3%A9gies-plans_0.pdf">https://developpementdurable.wallonie.be/sites/dd/files/2022-09/SWDD3_2022_CH2_strat%C3%A9gies-plans_0.pdf</a></p></td>
</tr>
<tr class="even even">
<td>Policy co-ordination tools at national level</td>
<td><p>There are a number of inter-governmental coordination mechanisms. A <a href="https://www.ejustice.just.fgov.be/cgi_loi/change_lg_2.pl?language=fr&amp;nm=1980080901&amp;la=F">Concertation Committee</a> has been made up with respect for linguistic parity:</p>
<ul>
<li><p>the Government represented by the Prime Minister and five of its members appointed by royal decree deliberated in the Council of Ministers;</p></li>
<li><p>the Flemish government represented by its minister president and one of its members;</p></li>
<li><p>the government of the French Community represented by its minister president</p></li>
<li><p>the government of the Walloon region represented by its minister president;</p></li>
<li><p>the government of the Brussels-Capital Region represented by its President and one of its members belonging to the other linguistic group.</p></li>
</ul>
<p>The local governments (municipalities, provinces) are represented by their associations in their respective region (a "united" national association also exists) and participate in committees at the federal level, although no formal consultation mechanism is in place.</p></td>
</tr>
<tr class="odd odd">
<td>Multi-level governance mechanisms between federal and subnational levels (e.g., institutional agreements, Committees, etc.)</td>
<td><p>The set of agreements on position-taking and representation in the EU was laid down in a cooperation agreement between the Belgian authorities in 1994. The starting point is the constitutional principle in foro interno, in foro externo, which extends the division of powers within Belgium to foreign policy. Such a cooperation agreement in which all governments co-decide and represent on an equal footing according to internal division of powers is completely unique in Europe. Since 1994, the agreement has been modified to a limited extent. However, the reforms of the Belgian state that further shift the centre of gravity towards the regional levels and the changes to the European system by the Lisbon Treaty require adjustments to this agreement.</p>
<p>Inter-ministerial conferences are the main governance bodies between the federal, regional and community levels. They include for instance the Interministerial conference on sustainable development and the Interministerial conference on foreign policy.</p></td>
</tr>
<tr class="even even">
<td>Policy co-ordination tools at regional level</td>
<td><p><strong>Wallonia</strong></p>
<p>There are several tools, usually linked to plans and strategies, including the Steering Committee of the Walloon Recovery Plan, the Walloon Partnership for Sustainable Development for the 3rd Walloon Sustainable Development Strategy and the Standing Conference on Territorial Development (CPDT)</p></td>
</tr>
<tr class="odd odd">
<td>Evaluation and monitoring tools</td>
<td><p><strong>Brussels-Capital Region</strong></p>
<p>The BISA is the reference centre for statistics for the Brussels-Capital Region. It identifies the authorities' needs and users' questions. In addition, BISA collects data from about 100 different suppliers (Federal, Regional, Communities, etc.) in order to develop, handle and produce public statistics completely independently. It carries out public policy evaluations entrusted to it by the Brussels-Capital Government or by order. These evaluations are a tool for taking decisions in order to improve the public policies implemented.</p>
<p>The structural embedding of spending reviews in the budgetary processes of the various entities of our country was included as a structural reform in the National Plan for Recovery and Resilience, becoming thus also an obligation, with concrete milestones and timing. From 2023, the goal is to integrate spending reviews into the budget process through the systematic inclusion of the results of spending reviews in annual and multi-year budget planning, starting from the preparation of the budget ordinance for the 2024 fiscal year. This will include ex-post quantification of the results, including savings, associated with the spending review programme.</p>
<p><strong>Flanders</strong></p>
<p>The implementation of the Flemish Recovery Plan is being closely monitored, using two measurement moments per year. The latest monitoring report submitted to the Flemish Government in February 2023 shows that the implementation of the Flemish resilience projects is very much on track: for instance, 97% of the projects are in execution following a decision by the Flemish Government or have been realised and 95% of the projects have been budgeted. The Flemish Government is also closely monitoring the recovery via the online dashboard: 36 indicators give a picture of the evolution of the economic and social situation in Flanders in 4 areas (macroeconomic and budgetary control, sustainable growth, inclusive growth, healthy growth).</p>
<p>The Flemish Broad Budgetary Reconsideration and expenditure reviews will become a structural evaluation practice in Flanders. With the adaptation of the Flemish Public Finance Codex in 2022, they were defined and structurally embedded in the Flemish budgetary process.</p>
<p><strong>Wallonia</strong></p>
<ul>
<li><p>Progress review on the SDGs</p></li>
<li><p>Evaluation programme of the Walloon Recovery Plan (IWEPS)</p></li>
<li><p>Work of the High Strategic Council on the ex-ante evaluation of employment, climate and poverty</p></li>
</ul></td>
</tr>
<tr class="even even">
<td>Future orientations of regional policy</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="regional-inequality-trends" class="level2">
<h2 class="anchored" data-anchor-id="regional-inequality-trends">Regional inequality trends</h2>
<p>Belgium experienced an increase in the Theil index of GDP per capita over 2000-2020. Inequality reached its maximum in 2020. The figures are normalized, with values in the year 2000 set to 1.</p>
<p>The Top 20%/Mean ratio was 0.032 higher in 2020 compared to 2000, indicating increased polarisation. The Bottom 20%/Mean ratio was 0.023 lower in the same period, indicating bottom divergence.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-a5f335c959bf53f2a2f9" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-a5f335c959bf53f2a2f9">{"x":{"data":[{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_gdppc:       NA<br />index_label: Theil index","time: 2001<br />index_gdppc:       NA<br />index_label: Theil index","time: 2002<br />index_gdppc:       NA<br />index_label: Theil index","time: 2003<br />index_gdppc:       NA<br />index_label: Theil index","time: 2004<br />index_gdppc:       NA<br />index_label: Theil index","time: 2005<br />index_gdppc:       NA<br />index_label: Theil index","time: 2006<br />index_gdppc:       NA<br />index_label: Theil index","time: 2007<br />index_gdppc:       NA<br />index_label: Theil index","time: 2008<br />index_gdppc:       NA<br />index_label: Theil index","time: 2009<br />index_gdppc:       NA<br />index_label: Theil index","time: 2010<br />index_gdppc:       NA<br />index_label: Theil index","time: 2011<br />index_gdppc:       NA<br />index_label: Theil index","time: 2012<br />index_gdppc:       NA<br />index_label: Theil index","time: 2013<br />index_gdppc:       NA<br />index_label: Theil index","time: 2014<br />index_gdppc:       NA<br />index_label: Theil index","time: 2015<br />index_gdppc:       NA<br />index_label: Theil index","time: 2016<br />index_gdppc:       NA<br />index_label: Theil index","time: 2017<br />index_gdppc:       NA<br />index_label: Theil index","time: 2018<br />index_gdppc:       NA<br />index_label: Theil index","time: 2019<br />index_gdppc:       NA<br />index_label: Theil index","time: 2020<br />index_gdppc:       NA<br />index_label: Theil index"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(227,0,19,1)","dash":"dash"},"hoveron":"points","name":"Theil index","legendgroup":"Theil index","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2001<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2002<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2003<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2004<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2005<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2006<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2007<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2008<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2009<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2010<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2011<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2012<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2013<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2014<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2015<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2016<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2017<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2018<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2019<br />index_gdppc:       NA<br />index_label: Top 20%/Mean","time: 2020<br />index_gdppc:       NA<br />index_label: Top 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(141,81,45,1)","dash":"dash"},"hoveron":"points","name":"Top 20%/Mean","legendgroup":"Top 20%/Mean","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2001<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2002<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2003<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2004<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2005<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2006<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2007<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2008<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2009<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2010<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2011<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2012<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2013<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2014<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2015<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2016<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2017<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2018<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2019<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean","time: 2020<br />index_gdppc:       NA<br />index_label: Bottom 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(222,156,98,1)","dash":"dash"},"hoveron":"points","name":"Bottom 20%/Mean","legendgroup":"Bottom 20%/Mean","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[1,1.0049061155786747,1.0206591034204022,1.0214188286488113,1.045610729311921,1.0598684099714937,1.0863391053802658,1.1173647632695658,1.1079042353684048,1.0737604879559106,1.0868020264440517,1.0976587043368884,1.094014549841628,1.0931752387891125,1.1055316555493242,1.1182006553401425,1.1253380358441827,1.1374875923517134,1.1513154449261034,1.1661083226005975,1.0909363420232925],"text":["time: 2000<br />index_gdppc: 1.000000<br />index_label: Mean GDP per capita","time: 2001<br />index_gdppc: 1.004906<br />index_label: Mean GDP per capita","time: 2002<br />index_gdppc: 1.020659<br />index_label: Mean GDP per capita","time: 2003<br />index_gdppc: 1.021419<br />index_label: Mean GDP per capita","time: 2004<br />index_gdppc: 1.045611<br />index_label: Mean GDP per capita","time: 2005<br />index_gdppc: 1.059868<br />index_label: Mean GDP per capita","time: 2006<br />index_gdppc: 1.086339<br />index_label: Mean GDP per capita","time: 2007<br />index_gdppc: 1.117365<br />index_label: Mean GDP per capita","time: 2008<br />index_gdppc: 1.107904<br />index_label: Mean GDP per capita","time: 2009<br />index_gdppc: 1.073760<br />index_label: Mean GDP per capita","time: 2010<br />index_gdppc: 1.086802<br />index_label: Mean GDP per capita","time: 2011<br />index_gdppc: 1.097659<br />index_label: Mean GDP per capita","time: 2012<br />index_gdppc: 1.094015<br />index_label: Mean GDP per capita","time: 2013<br />index_gdppc: 1.093175<br />index_label: Mean GDP per capita","time: 2014<br />index_gdppc: 1.105532<br />index_label: Mean GDP per capita","time: 2015<br />index_gdppc: 1.118201<br />index_label: Mean GDP per capita","time: 2016<br />index_gdppc: 1.125338<br />index_label: Mean GDP per capita","time: 2017<br />index_gdppc: 1.137488<br />index_label: Mean GDP per capita","time: 2018<br />index_gdppc: 1.151315<br />index_label: Mean GDP per capita","time: 2019<br />index_gdppc: 1.166108<br />index_label: Mean GDP per capita","time: 2020<br />index_gdppc: 1.090936<br />index_label: Mean GDP per capita"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(26,154,189,1)","dash":"dash"},"hoveron":"points","name":"Mean GDP per capita","legendgroup":"Mean GDP per capita","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_top_mean:       NA<br />index_label: Theil index","time: 2001<br />index_top_mean:       NA<br />index_label: Theil index","time: 2002<br />index_top_mean:       NA<br />index_label: Theil index","time: 2003<br />index_top_mean:       NA<br />index_label: Theil index","time: 2004<br />index_top_mean:       NA<br />index_label: Theil index","time: 2005<br />index_top_mean:       NA<br />index_label: Theil index","time: 2006<br />index_top_mean:       NA<br />index_label: Theil index","time: 2007<br />index_top_mean:       NA<br />index_label: Theil index","time: 2008<br />index_top_mean:       NA<br />index_label: Theil index","time: 2009<br />index_top_mean:       NA<br />index_label: Theil index","time: 2010<br />index_top_mean:       NA<br />index_label: Theil index","time: 2011<br />index_top_mean:       NA<br />index_label: Theil index","time: 2012<br />index_top_mean:       NA<br />index_label: Theil index","time: 2013<br />index_top_mean:       NA<br />index_label: Theil index","time: 2014<br />index_top_mean:       NA<br />index_label: Theil index","time: 2015<br />index_top_mean:       NA<br />index_label: Theil index","time: 2016<br />index_top_mean:       NA<br />index_label: Theil index","time: 2017<br />index_top_mean:       NA<br />index_label: Theil index","time: 2018<br />index_top_mean:       NA<br />index_label: Theil index","time: 2019<br />index_top_mean:       NA<br />index_label: Theil index","time: 2020<br />index_top_mean:       NA<br />index_label: Theil index"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(227,0,19,1)","dash":"dash"},"hoveron":"points","name":"Theil index","legendgroup":"Theil index","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[1,1.0140893510490769,1.0035906680113249,1.0168833333260041,1.0267190479067128,1.0255590338780096,1.0122084809864462,1.0039514517948045,1.0088081498780275,1.0236295112570628,1.0247685523173646,1.0024312464802192,1.0126986005014933,1.0122696915361522,1.0113710200500128,1.0156840903111495,1.0122424969921,1.0123725216164248,1.0151486539227279,1.0260349142348482,1.0322054028936645],"text":["time: 2000<br />index_top_mean: 1.000000<br />index_label: Top 20%/Mean","time: 2001<br />index_top_mean: 1.014089<br />index_label: Top 20%/Mean","time: 2002<br />index_top_mean: 1.003591<br />index_label: Top 20%/Mean","time: 2003<br />index_top_mean: 1.016883<br />index_label: Top 20%/Mean","time: 2004<br />index_top_mean: 1.026719<br />index_label: Top 20%/Mean","time: 2005<br />index_top_mean: 1.025559<br />index_label: Top 20%/Mean","time: 2006<br />index_top_mean: 1.012208<br />index_label: Top 20%/Mean","time: 2007<br />index_top_mean: 1.003951<br />index_label: Top 20%/Mean","time: 2008<br />index_top_mean: 1.008808<br />index_label: Top 20%/Mean","time: 2009<br />index_top_mean: 1.023630<br />index_label: Top 20%/Mean","time: 2010<br />index_top_mean: 1.024769<br />index_label: Top 20%/Mean","time: 2011<br />index_top_mean: 1.002431<br />index_label: Top 20%/Mean","time: 2012<br />index_top_mean: 1.012699<br />index_label: Top 20%/Mean","time: 2013<br />index_top_mean: 1.012270<br />index_label: Top 20%/Mean","time: 2014<br />index_top_mean: 1.011371<br />index_label: Top 20%/Mean","time: 2015<br />index_top_mean: 1.015684<br />index_label: Top 20%/Mean","time: 2016<br />index_top_mean: 1.012242<br />index_label: Top 20%/Mean","time: 2017<br />index_top_mean: 1.012373<br />index_label: Top 20%/Mean","time: 2018<br />index_top_mean: 1.015149<br />index_label: Top 20%/Mean","time: 2019<br />index_top_mean: 1.026035<br />index_label: Top 20%/Mean","time: 2020<br />index_top_mean: 1.032205<br />index_label: Top 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(141,81,45,1)","dash":"dash"},"hoveron":"points","name":"Top 20%/Mean","legendgroup":"Top 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2001<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2002<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2003<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2004<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2005<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2006<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2007<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2008<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2009<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2010<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2011<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2012<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2013<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2014<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2015<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2016<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2017<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2018<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2019<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean","time: 2020<br />index_top_mean:       NA<br />index_label: Bottom 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(222,156,98,1)","dash":"dash"},"hoveron":"points","name":"Bottom 20%/Mean","legendgroup":"Bottom 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2001<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2002<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2003<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2004<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2005<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2006<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2007<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2008<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2009<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2010<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2011<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2012<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2013<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2014<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2015<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2016<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2017<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2018<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2019<br />index_top_mean:       NA<br />index_label: Mean GDP per capita","time: 2020<br />index_top_mean:       NA<br />index_label: Mean GDP per capita"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(26,154,189,1)","dash":"dash"},"hoveron":"points","name":"Mean GDP per capita","legendgroup":"Mean GDP per capita","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2001<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2002<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2003<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2004<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2005<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2006<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2007<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2008<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2009<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2010<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2011<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2012<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2013<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2014<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2015<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2016<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2017<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2018<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2019<br />index_bottom_mean:        NA<br />index_label: Theil index","time: 2020<br />index_bottom_mean:        NA<br />index_label: Theil index"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(227,0,19,1)","dash":"dash"},"hoveron":"points","name":"Theil index","legendgroup":"Theil index","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2001<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2002<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2003<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2004<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2005<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2006<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2007<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2008<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2009<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2010<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2011<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2012<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2013<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2014<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2015<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2016<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2017<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2018<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2019<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean","time: 2020<br />index_bottom_mean:        NA<br />index_label: Top 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(141,81,45,1)","dash":"dash"},"hoveron":"points","name":"Top 20%/Mean","legendgroup":"Top 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[1,0.99877430875595208,0.98423000540341654,0.97977403194202684,0.98225865875400009,0.98138478436261001,0.98249619485108264,0.98663742523480324,0.99999776686145292,0.98720558872875097,0.98656879167297096,1.0016075651540799,0.99572063000855382,0.99042471977539914,0.99652564604986538,0.99181157792740104,0.98575800555840876,0.98465210486357735,0.99026696897027711,0.9793137062353271,0.97738499881326357],"text":["time: 2000<br />index_bottom_mean: 1.0000000<br />index_label: Bottom 20%/Mean","time: 2001<br />index_bottom_mean: 0.9987743<br />index_label: Bottom 20%/Mean","time: 2002<br />index_bottom_mean: 0.9842300<br />index_label: Bottom 20%/Mean","time: 2003<br />index_bottom_mean: 0.9797740<br />index_label: Bottom 20%/Mean","time: 2004<br />index_bottom_mean: 0.9822587<br />index_label: Bottom 20%/Mean","time: 2005<br />index_bottom_mean: 0.9813848<br />index_label: Bottom 20%/Mean","time: 2006<br />index_bottom_mean: 0.9824962<br />index_label: Bottom 20%/Mean","time: 2007<br />index_bottom_mean: 0.9866374<br />index_label: Bottom 20%/Mean","time: 2008<br />index_bottom_mean: 0.9999978<br />index_label: Bottom 20%/Mean","time: 2009<br />index_bottom_mean: 0.9872056<br />index_label: Bottom 20%/Mean","time: 2010<br />index_bottom_mean: 0.9865688<br />index_label: Bottom 20%/Mean","time: 2011<br />index_bottom_mean: 1.0016076<br />index_label: Bottom 20%/Mean","time: 2012<br />index_bottom_mean: 0.9957206<br />index_label: Bottom 20%/Mean","time: 2013<br />index_bottom_mean: 0.9904247<br />index_label: Bottom 20%/Mean","time: 2014<br />index_bottom_mean: 0.9965256<br />index_label: Bottom 20%/Mean","time: 2015<br />index_bottom_mean: 0.9918116<br />index_label: Bottom 20%/Mean","time: 2016<br />index_bottom_mean: 0.9857580<br />index_label: Bottom 20%/Mean","time: 2017<br />index_bottom_mean: 0.9846521<br />index_label: Bottom 20%/Mean","time: 2018<br />index_bottom_mean: 0.9902670<br />index_label: Bottom 20%/Mean","time: 2019<br />index_bottom_mean: 0.9793137<br />index_label: Bottom 20%/Mean","time: 2020<br />index_bottom_mean: 0.9773850<br />index_label: Bottom 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(222,156,98,1)","dash":"dash"},"hoveron":"points","name":"Bottom 20%/Mean","legendgroup":"Bottom 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2001<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2002<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2003<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2004<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2005<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2006<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2007<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2008<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2009<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2010<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2011<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2012<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2013<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2014<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2015<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2016<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2017<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2018<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2019<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita","time: 2020<br />index_bottom_mean:        NA<br />index_label: Mean GDP per capita"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(26,154,189,1)","dash":"dash"},"hoveron":"points","name":"Mean GDP per capita","legendgroup":"Mean GDP per capita","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[1,1.0072711016487856,1.0377011480964098,1.1255538325088881,1.1759192150712248,1.1589484574569631,1.1511336119395645,1.1897362436130585,1.1371464942276881,1.1364534055554365,1.1627132123906283,1.1306878253838017,1.2105905880870556,1.2131316449199607,1.2076492783997146,1.2484745573455875,1.3147756377868256,1.3225654949404599,1.3175688831869727,1.3584065282630835,1.387333906955919],"text":["time: 2000<br />index_theil: 1.000000<br />index_label: Theil index","time: 2001<br />index_theil: 1.007271<br />index_label: Theil index","time: 2002<br />index_theil: 1.037701<br />index_label: Theil index","time: 2003<br />index_theil: 1.125554<br />index_label: Theil index","time: 2004<br />index_theil: 1.175919<br />index_label: Theil index","time: 2005<br />index_theil: 1.158948<br />index_label: Theil index","time: 2006<br />index_theil: 1.151134<br />index_label: Theil index","time: 2007<br />index_theil: 1.189736<br />index_label: Theil index","time: 2008<br />index_theil: 1.137146<br />index_label: Theil index","time: 2009<br />index_theil: 1.136453<br />index_label: Theil index","time: 2010<br />index_theil: 1.162713<br />index_label: Theil index","time: 2011<br />index_theil: 1.130688<br />index_label: Theil index","time: 2012<br />index_theil: 1.210591<br />index_label: Theil index","time: 2013<br />index_theil: 1.213132<br />index_label: Theil index","time: 2014<br />index_theil: 1.207649<br />index_label: Theil index","time: 2015<br />index_theil: 1.248475<br />index_label: Theil index","time: 2016<br />index_theil: 1.314776<br />index_label: Theil index","time: 2017<br />index_theil: 1.322565<br />index_label: Theil index","time: 2018<br />index_theil: 1.317569<br />index_label: Theil index","time: 2019<br />index_theil: 1.358407<br />index_label: Theil index","time: 2020<br />index_theil: 1.387334<br />index_label: Theil index"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(227,0,19,1)","dash":"solid"},"hoveron":"points","name":"Theil index","legendgroup":"Theil index","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2001<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2002<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2003<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2004<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2005<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2006<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2007<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2008<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2009<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2010<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2011<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2012<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2013<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2014<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2015<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2016<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2017<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2018<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2019<br />index_theil:       NA<br />index_label: Top 20%/Mean","time: 2020<br />index_theil:       NA<br />index_label: Top 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(141,81,45,1)","dash":"solid"},"hoveron":"points","name":"Top 20%/Mean","legendgroup":"Top 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2001<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2002<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2003<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2004<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2005<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2006<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2007<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2008<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2009<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2010<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2011<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2012<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2013<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2014<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2015<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2016<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2017<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2018<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2019<br />index_theil:       NA<br />index_label: Bottom 20%/Mean","time: 2020<br />index_theil:       NA<br />index_label: Bottom 20%/Mean"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(222,156,98,1)","dash":"solid"},"hoveron":"points","name":"Bottom 20%/Mean","legendgroup":"Bottom 20%/Mean","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"text":["time: 2000<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2001<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2002<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2003<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2004<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2005<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2006<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2007<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2008<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2009<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2010<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2011<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2012<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2013<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2014<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2015<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2016<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2017<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2018<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2019<br />index_theil:       NA<br />index_label: Mean GDP per capita","time: 2020<br />index_theil:       NA<br />index_label: Mean GDP per capita"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(26,154,189,1)","dash":"solid"},"hoveron":"points","name":"Mean GDP per capita","legendgroup":"Mean GDP per capita","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":25.570776255707766,"l":43.105022831050235},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Figure 1: Trends in GDP per capita inequality indicators,<br />TL3 OECD regions","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[2000,2020],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.95688755340613085,1.4078313523630517],"tickmode":"array","ticktext":["1.0","1.1","1.2","1.3","1.4"],"tickvals":[1,1.1000000000000001,1.2,1.3,1.3999999999999999],"categoryorder":"array","categoryarray":["1.0","1.1","1.2","1.3","1.4"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Statistic (2000=1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"source":"A","attrs":{"c3896fbbfe6e":{"x":{},"y":{},"colour":{},"type":"scatter"},"c3894304a522":{"x":{},"y":{},"colour":{}},"c38955316360":{"x":{},"y":{},"colour":{}},"c3895292458":{"x":{},"y":{},"colour":{}}},"cur_data":"c3896fbbfe6e","visdat":{"c3896fbbfe6e":["function (y) ","x"],"c3894304a522":["function (y) ","x"],"c38955316360":["function (y) ","x"],"c3895292458":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="oecdnote">
<p><strong>Note</strong>: Top/bottom calculated as population equivalent (top/bottom regions with at least 20% of the population). The interpretation of top/bottom 20% GDP per capita is that 20% of the population in the country holds 20% of the value. Top 20%/Mean calculated as mean GDP per capita in top 20% regions over mean TL3 GDP per capita in a given year. Bottom 20%/Mean calculated as mean TL3 GDP per capita in bottom 20% regions over mean TL3 GDP per capita in a given year. To improve data consistency, input series are aggregated when TL3 regions are part of the same FUA. To improve time series, TL3 missing values have been estimated based on the evolution at higher geographic level.</p>
<p><strong>Source</strong>: OECD Regional Database (2022).</p>
</div>
<p>In 2020, the gap in GDP per capita between large metropolitan and non-large metropolitan regions was 1.615. For reference, the same value for OECD was 1.475. This gap increased by 0.025 percentage points between 2000 and 2020.</p>
<p>Meanwhile, in 2020, the gap in GDP per capita between metropolitan and non-metropolitan regions was 1.135. For reference, the same value for OECD was 1.325. This gap increased by 0.006 percentage points since 2000.</p>
<p>In turn, the gap in GDP per capita between regions near and far a Functional Urban Area (FUA) of more than 250 thousand inhabitants was 1.163 in 2020 and increased by 0.048 percentage points since 2000.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-80c47f551c792a0a483f" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-80c47f551c792a0a483f">{"x":{"data":[{"orientation":"v","width":[0.27000000000000002,0.27000000000000002,0.27000000000000046],"base":[0,0,0],"x":[0.70000000000000007,1.6999999999999997,2.7000000000000002],"y":[1.5902442025969674,1.1292616767358914,1.1149854433096076],"text":["series: Large metropolitan/Non-large<br />gap: 1.590244<br />time: 2000","series: Metropolitan/Non-metropolitan<br />gap: 1.129262<br />time: 2000","series: Near/Far from a FUA >250K<br />gap: 1.114985<br />time: 2000"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(84,153,184,1)","line":{"width":5.6692913385826778,"color":"transparent"}},"name":"2000","legendgroup":"2000","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.27000000000000002,0.27000000000000024,0.27000000000000046],"base":[0,0,0],"x":[1,2,3],"y":[1.6153018968034136,1.1351241967895613,1.1627667986171328],"text":["series: Large metropolitan/Non-large<br />gap: 1.615302<br />time: 2020","series: Metropolitan/Non-metropolitan<br />gap: 1.135124<br />time: 2020","series: Near/Far from a FUA >250K<br />gap: 1.162767<br />time: 2020"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(194,147,101,1)","line":{"width":5.6692913385826778,"color":"transparent"}},"name":"2020","legendgroup":"2020","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.27000000000000002,0.27000000000000046,0.27000000000000046],"base":[0,0,0],"x":[1.2999999999999998,2.2999999999999998,3.2999999999999998],"y":[1.4753552782655139,1.3249142150196771,1.3026981198358973],"text":["series: Large metropolitan/Non-large<br />gap: 1.475355<br />time: OECD mean gap, 2020","series: Metropolitan/Non-metropolitan<br />gap: 1.324914<br />time: OECD mean gap, 2020","series: Near/Far from a FUA >250K<br />gap: 1.302698<br />time: OECD mean gap, 2020"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(157,53,62,1)","line":{"width":5.6692913385826778,"color":"transparent"}},"name":"OECD mean gap, 2020","legendgroup":"OECD mean gap, 2020","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Figure 2: GDP per capita gap by type of region<br />compared to the OECD average","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["Large metropolitan/Non-large","Metropolitan/Non-metropolitan","Near/Far from a FUA >250K"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["Large metropolitan/Non-large","Metropolitan/Non-metropolitan","Near/Far from a FUA >250K"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-30,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Category","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.080765094840170693,1.6960669916435842],"tickmode":"array","ticktext":["0.0","0.5","1.0","1.5"],"tickvals":[0,0.5,1,1.5],"categoryorder":"array","categoryarray":["0.0","0.5","1.0","1.5"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Gap","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"source":"A","attrs":{"c389507a62e7":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"c389507a62e7","visdat":{"c389507a62e7":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="oecdnote">
<p><strong>Note</strong>: Far from a FUA&gt;250K includes regions near/with a small FUA and remote regions. OECD mean gap based on 1 586 TL3 regions in 27 countries with available data (no TL3 data for Australia, Canada, Chile, Colombia, Costa Rica, Iceland, Ireland, Israel, Mexico, Luxembourg and Switzerland).</p>
<p><strong>Source</strong>: OECD Regional Database (2022).</p>
</div>
<p>In Belgium, the gap between the upper and the lower half of regions in terms of labour productivity increased between 2001 and 2019. Over this period labour productivity in the upper half of regions grew roughly by 15%, 6 percentage points more than in the lower half of regions. During 2020, the gap narrowed down. Nevertheless, more years of data are necessary to determine the long-term impact of the COVID-19 pandemic on labour productivity gaps in regions.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-86d8e3f6fc892e9cd808" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-86d8e3f6fc892e9cd808">{"x":{"data":[{"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019],"y":[75273.2890625,76099.1796875,75531.75,76715.5390625,77294.9921875,78679.1953125,80283.5625,80503.6328125,78215.734375,79233.2109375,81069.09375,80249.5546875,80492.515625,82009.640625,82018.9453125,81337.4296875,80998.703125,81940.4140625,81649.640625],"text":["time: 2001<br />value:  75273.29<br />series: Lower half","time: 2002<br />value:  76099.18<br />series: Lower half","time: 2003<br />value:  75531.75<br />series: Lower half","time: 2004<br />value:  76715.54<br />series: Lower half","time: 2005<br />value:  77294.99<br />series: Lower half","time: 2006<br />value:  78679.20<br />series: Lower half","time: 2007<br />value:  80283.56<br />series: Lower half","time: 2008<br />value:  80503.63<br />series: Lower half","time: 2009<br />value:  78215.73<br />series: Lower half","time: 2010<br />value:  79233.21<br />series: Lower half","time: 2011<br />value:  81069.09<br />series: Lower half","time: 2012<br />value:  80249.55<br />series: Lower half","time: 2013<br />value:  80492.52<br />series: Lower half","time: 2014<br />value:  82009.64<br />series: Lower half","time: 2015<br />value:  82018.95<br />series: Lower half","time: 2016<br />value:  81337.43<br />series: Lower half","time: 2017<br />value:  80998.70<br />series: Lower half","time: 2018<br />value:  81940.41<br />series: Lower half","time: 2019<br />value:  81649.64<br />series: Lower half"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(23,125,199,1)","dash":"solid"},"hoveron":"points","name":"Lower half","legendgroup":"Lower half","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019],"y":[93823.59375,95873.453125,96383.5390625,98628.265625,99665.9375,100836.34375,102865.0625,101541.15625,100009.21875,102413.3359375,102645.2578125,103347.8984375,104097.375,105211.34375,106902.1875,106697.7734375,106870.9921875,106991.4453125,107840.3515625],"text":["time: 2001<br />value:  93823.59<br />series: Upper half","time: 2002<br />value:  95873.45<br />series: Upper half","time: 2003<br />value:  96383.54<br />series: Upper half","time: 2004<br />value:  98628.27<br />series: Upper half","time: 2005<br />value:  99665.94<br />series: Upper half","time: 2006<br />value: 100836.34<br />series: Upper half","time: 2007<br />value: 102865.06<br />series: Upper half","time: 2008<br />value: 101541.16<br />series: Upper half","time: 2009<br />value: 100009.22<br />series: Upper half","time: 2010<br />value: 102413.34<br />series: Upper half","time: 2011<br />value: 102645.26<br />series: Upper half","time: 2012<br />value: 103347.90<br />series: Upper half","time: 2013<br />value: 104097.38<br />series: Upper half","time: 2014<br />value: 105211.34<br />series: Upper half","time: 2015<br />value: 106902.19<br />series: Upper half","time: 2016<br />value: 106697.77<br />series: Upper half","time: 2017<br />value: 106870.99<br />series: Upper half","time: 2018<br />value: 106991.45<br />series: Upper half","time: 2019<br />value: 107840.35<br />series: Upper half"],"type":"scatter","mode":"lines","line":{"width":4.5354330708661417,"color":"rgba(80,133,81,1)","dash":"solid"},"hoveron":"points","name":"Upper half","legendgroup":"Upper half","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":25.570776255707766,"l":66.484018264840202},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Figure 3: Evolution of labour productivity, TL3 regions","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[2000.0999999999999,2019.9000000000001],"tickmode":"array","ticktext":["2001","2003","2005","2007","2009","2011","2013","2015","2017","2019"],"tickvals":[2001,2003,2005,2007,2009,2011,2013,2015,2017,2019],"categoryorder":"array","categoryarray":["2001","2003","2005","2007","2009","2011","2013","2015","2017","2019"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[73644.935937500006,109468.70468749999],"tickmode":"array","ticktext":["80 000","90 000","100 000"],"tickvals":[80000,90000,100000],"categoryorder":"array","categoryarray":["80 000","90 000","100 000"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.6529680365296811,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Productivity (2015 USD PPP)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"Series","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"source":"A","attrs":{"c3891c985a40":{"x":{},"y":{},"colour":{},"type":"scatter"}},"cur_data":"c3891c985a40","visdat":{"c3891c985a40":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="oecdnote">
<p><strong>Note</strong>: A region is in the “upper half” if labour productivity was above the country median in the first year with available data and “lower half” if productivity was below the country median. Labour productivity in each group is equal to the sum of Gross Value Added, expressed in USD at constant prices and PPP (base year 2015) within the group, divided by the sum of total employment in regions within the group. Regions are small (TL3) regions, except for Australia, Canada, Chile, Colombia, Ireland, Mexico, Norway, Switzerland, Turkey and the United States where they are large (TL2) regions due to data availability.</p>
<p><strong>Source</strong>: OECD Regional Database (2022).</p>
</div>
<p>Regions where the economic activity shifts towards tradable activities, such as industry and tradable services, tend to grow faster in terms of labour productivity. In Belgium, between 2001 and 2020, the share of workers in the industrial sector went down in all regions but more so in regions that used to be in the upper half of the labour productivity distribution. At the same time, the share of workers in the tradable services sector went up in all regions but more so in regions that were already in the upper half of the labour productivity distribution. Hence, the evolution of employment shares in the tradable services sector widened the labour productivity gap between regions while the opposite was true for the industrial sector.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ddf052891e12f0268d89" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-ddf052891e12f0268d89">{"x":{"data":[{"x":["Lower half"],"y":[17.381345748901371],"type":"bar","name":"Lower half 2020","marker":{"color":"#177dc7","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Upper half"],"y":[16.46433258056641],"type":"bar","name":"Upper half 2020","marker":{"color":"#508551","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Lower half"],"y":[12.91833591461182],"type":"scatter","mode":"markers","name":"Lower half 2001","marker":{"color":"#6bc5f2","size":12,"symbol":"diamond-dot","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"line":{"color":"rgba(102,194,165,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Upper half"],"y":[11.170571327209471],"type":"scatter","mode":"markers","name":"Upper half 2001","marker":{"color":"#c8f075","size":12,"symbol":"diamond-dot","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"line":{"color":"rgba(141,160,203,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Lower half"],"y":[13.405013084411619],"type":"bar","marker":{"color":"#177dc7","line":{"color":"rgba(102,194,165,1)"}},"showlegend":false,"name":"Lower half","textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"xaxis":"x2","yaxis":"y","frame":null},{"x":["Upper half"],"y":[21.395658493041989],"type":"bar","marker":{"color":"#508551","line":{"color":"rgba(141,160,203,1)"}},"showlegend":false,"name":"Upper half","textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"xaxis":"x2","yaxis":"y","frame":null},{"x":["Lower half"],"y":[18.00327301025391],"type":"scatter","mode":"markers","marker":{"color":"#6bc5f2","size":12,"symbol":"diamond-dot","line":{"color":"rgba(102,194,165,1)"}},"showlegend":false,"name":"Lower half","textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"line":{"color":"rgba(102,194,165,1)"},"xaxis":"x2","yaxis":"y","frame":null},{"x":["Upper half"],"y":[27.40189170837402],"type":"scatter","mode":"markers","marker":{"color":"#c8f075","size":12,"symbol":"diamond-dot","line":{"color":"rgba(141,160,203,1)"}},"showlegend":false,"name":"Upper half","textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"line":{"color":"rgba(141,160,203,1)"},"xaxis":"x2","yaxis":"y","frame":null}],"layout":{"xaxis":{"domain":[0,0.45000000000000001],"automargin":true,"title":"","visible":false,"type":"category","categoryorder":"array","categoryarray":["Lower half","Upper half"],"anchor":"y"},"xaxis2":{"domain":[0.55000000000000004,1],"automargin":true,"title":"","visible":false,"type":"category","categoryorder":"array","categoryarray":["Lower half","Upper half"],"anchor":"y"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Employment share (%)","anchor":"x"},"annotations":[{"x":0.25,"y":1,"font":{"size":14},"text":"Industry","xref":"paper","yref":"paper","xanchor":"center","yanchor":"bottom","showarrow":false},{"x":0.75,"y":1,"font":{"size":14},"text":"Services","xref":"paper","yref":"paper","xanchor":"center","yanchor":"bottom","showarrow":false}],"shapes":[],"images":[],"margin":{"b":50,"l":50,"t":120,"r":50,"pad":4},"title":{"text":"Figure 4: Share of workers in most productive (tradable) sectors,<br />TL3 regions","x":0},"legend":{"bgcolor":"rgb(242, 242, 242)"},"hovermode":"closest","showlegend":true},"attrs":{"c3896f3687ba":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"color":{},"type":"bar","name":{},"marker":{"color":["#177dc7","#508551"]},"inherit":true},"c3896f3687ba.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"markers","color":{},"name":{},"marker":{"color":["#6bc5f2","#c8f075"],"size":12,"symbol":"diamond-dot"},"inherit":true},"c38916695347":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"color":{},"type":"bar","marker":{"color":["#177dc7","#508551"]},"showlegend":false,"inherit":true},"c38916695347.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"markers","color":{},"marker":{"color":["#6bc5f2","#c8f075"],"size":12,"symbol":"diamond-dot"},"showlegend":false,"inherit":true}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false,"displayModeBar":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="oecdnote">
<p><strong>Note</strong>: A region is in the “upper half” if labour productivity was above the country median in the first year with available data and “lower half” if productivity was below the country median. The share of workers in a given sector for a group of regions is defined as the sum of employment in that sector within the group divided by the sum of total employment within the group. Regions are small (TL3) regions, except for Australia, Canada, Chile, Ireland, Mexico, Norway, Switzerland, Turkey and the United States where they are large (TL2) regions due to data availability. Industry includes the following tradable goods sectors: Mining and quarrying (B), Manufacturing (C), Electricity, gas, steam and air conditioning supply (D) and Water supply; sewerage; waste management and remediation activities (E) NACE macro sectors. Tradable services include Information and communication (J), Financial and insurance activities (K), Real estate activities (L), Professional, scientific and technical activities (M), Administrative and support service activities (N).</p>
<p><strong>Source</strong>: OECD Regional Database (2022).</p>
</div>
</section>
<section id="recent-policy-developments" class="level2">
<h2 class="anchored" data-anchor-id="recent-policy-developments">Recent policy developments</h2>
<div class="cell">
<div class="cell-output-display">

<p><strong>Brussels-Capital Region</strong></p> <p>The support measures taken by the Brussels Government in the recent months and years have taken to deal with the Covid-19</p> <p>pandemic and the consequences of the war in Ukraine, as well as the targeted measures the Government decided for the year 2023 to deal with the inflation we are currently experiencing, have and will have an impact on the financial situation of the</p> <p>Region. Despite these developments, it remains the objective of the Brussels Government to return to a balanced budget in 2024. The multi-year rationalisation processes aimed at greater efficiency and effectiveness of public spending (in particular through spending reviews) will be continued.</p> <p>With " Shifting Economy " the Brussels government is paving the way for the transformation of the Brussels economy to make it carbon-free, regenerative, circular, social, democratic and digital. In order not to stifle economic recovery and promote a sustainable inclusive growth, the Brussels Government continues to invest in mobility, social housing employment policy and the implementation of the climate plan. To finance the relaunch, the Brussels Capital Region make maximum use of the Facility for Recovery and Resilience.</p> <p>As stated in the 2019-2024 General Policy Statement, the Government intends to make two changes in social and health policies: a social shift aimed at reducing social inequalities and an organizational shift aimed at better organizing healthcare and social action, ensuring accessibility, quality, and sustainability of care.</p> <p>This dual shift is implemented within a global program embodied by the Brussels Integrated Social-Health Plan (PSSI), which is common to the (Common Community Commission) COCOM and the COCOF (French Community Commission)), regarding social action and health.</p> <p>The PSSI, adopted in July 2022, proposes a framework aiming to involve all services present on the territory to direct social-health policies in an integrated and coherent manner, in a logic of territorial basins and neighbourhood groups.</p> <p>It is structured around four axes:</p> <ul> <li><p>Improving quality of life and health and reducing social health inequalities;</p></li> <li><p>Guaranteeing access to rights and services;</p></li> <li><p>Improving the structure and coordination of aid and care services ;</p></li> <li><p>Co-building an integrated social-health policy.</p></li> </ul> <p>In terms of gender equality, in December 2022 the Brussels government adopted the first Brussels plan for gender mainstreaming and equality between women and men. Supported by the voluntary sector, which was largely involved in its development, this Plan proposes 69 very concrete cross-cutting actions to ensure better inclusion of the gender dimension in public policies.</p> <p>The new management contracts of Actiris and Bruxelles Formation for the period 2023-2027 will contribute to the commitment made by Belgium to achieve, by 2030, an employment rate of over 80% for people aged 20 to 64. In addition, the Go4Brussels 2030 strategy aims to "guarantee access to stable and sustainable employment for all". In this context, a specific initiative is dedicated to combating discrimination in hiring and promoting diversity. The principles and essential rights included in the European Pillar of Social Rights (chapter "equal opportunities and access to the labour market") that promote the development of fair and effective labour markets and social protection systems, also play a crucial role in this respect and aim to ensure that all Brussels talents have equal access to stable and quality employment. In addition, the regional Employment Qualification strategy will be launched in 2023 with a view to further strengthening the level of skills of job seekers and meeting the growing demands of the metropolitan labour market. In 2023, the Brussels Government aims to modernize the matter of paid educational leave in order to make it an effective training tool throughout one's career and to make it more accessible and inclusive (gender, disability, online training, part-time workers, etc.). Finally, an evaluation of all employment aids (including those specifically aimed at job seekers and workers with disabilities) is being finalized and could lead to the revision of certain regulations in order to adapt them to the current realities of the job market, benefiting job seekers who are far from the labour market.</p> <p><strong>Flanders</strong></p> <p>The Flemish government is resolutely opting to keep public finances healthy and strengthen structural growth in our country. A budgetary path has been mapped out whereby Flanders returns to a balanced budget from 2027 onwards (excluding the investment expenditure related to Oosterweel).</p> <p>The Flemish Broad Budgetary Review and expenditure reviews are not one-off or non-binding exercises but will become a structural evaluation practice in Flanders. With the adaptation of the Flemish Public Finance Codex in 2022, they were defined and structurally embedded in the Flemish budgetary process.</p> <p>Meanwhile, the Resilience Plan totalling €4.3 billion is being implemented, including the 55 projects funded by European RRF funds. Despite the five COVID-19 waves and the crisis in Ukraine, the implementation of the Flemish Resilience plan is going largely as planned. 96% of the projects are on schedule; 92% of the initiated milestones have been achieved or are on schedule.</p> <p>As said the Flemish Government aims to achieve an 80% employment rate by 2030, in line with the targets in the European Pillar of Social Rights. In 2022, Flanders reached an employment rate of 76.7% for the 20-64 age group.The current Flemish labour market is characterised by a high labour market tightness with labour shortages in some sectors. To ease these shortages and to work towards the 2030 target of 80%, the Flemish Government and the Flemish social partners concluded a new employment agreement ‘Iedereen nodig, Iedereen mee’ in 2022.</p> <p>The employment agreement consists of four pillars: results-oriented active labour market policies form the first pillar. Measures from the agreement include the introduction of a social security contribution reduction for employers that hire someone without recent lasting work experience.</p> <p>On the topic of active labour market policies, the Flemish Government has also introduced the ‘jobbonus’ to increase the financial difference between working and not working. It is a cash premium for people with a low labour income. To achieve an employment rate of 80%, some more vulnerable groups need to be included in the labour market as well. Flanders is introducing ‘individual adapted work’ (individueel maatwerk), a tailored employment support system for people with health conditions and/or occupational disabilities.</p> <p>The second pillar revolves around lifelong learning, upskilling and reskilling people to get the right skills for current and future jobs. In 2021, the Action plan for Lifelong Learning was launched, which provides a coherent and mobilising framework for all partners involved in the realisation of a learning culture in Flanders. The Flemish Government wants to reach a 60% rate for training participation by 2030. The third pillar is about ‘workable’ jobs, and improving the quality of work, to enable longer and more fulfilling careers. The fourth and last pillar is centred around economic migration and interregional mobility, which can provide opportunities in a tight labour market.</p> <p>With Flanders Technology &amp; Innovation, Flanders presents itself as the technology laboratory of the world and aims to tackle five major societal challenges: climate and energy (energy tech), health (health tech), education and labour market (Flanders Next Academy), data and digitisation (data tech) and entertainment and media (entertainment tech). Five thematic symposia will be organised around these themes. Major public events are then planned in March 2024, spread across the five Flemish provinces.</p> <p><strong>Wallonia</strong></p> <p><strong>Launch of the Walloon Recovery Plan thanks to the pooling of three action programmes (<em>Get up Walonia</em>, <em>Walloon Transition Plan</em>, <em>Facility for Recovery and Resilience</em>). The Walloon recovery plan has been completed with a 6<sup>th</sup> strategic axis focusing exclusively on the reconstruction of the disaster areas affected by the extreme weather of July 2021.</strong></p>
</div>
</div>

<table border="1" style="width:75%;margin-left:auto;margin-right:auto;">
<tbody><tr>
<th style="background:#d4edff; padding:10px;font-size:9.0pt;" valign="center">
Territorial definitions
</th>
</tr>
<tr>
<td>
<p style="padding-left:10px;padding-right:10px;padding-top:10px;font-size:9.0pt;">
The data in this note reflect different sub-national geographic levels in OECD countries. In particular, <b>regions</b> are classified on two territorial levels reflecting the administrative organisation of countries: large regions (TL2) and small regions (TL3).
</p>
<p style="padding-left:10px;padding-right:10px;font-size:9.0pt;">
Small regions are classified according to their access to metropolitan areas (Fadic et al.&nbsp;2019).&nbsp;The typology classifies small (TL3) regions into metropolitan and non-metropolitan regions according to the following criteria:
</p>
<ul style="list-style-type:circle;font-size:9.0pt;padding-right:10px">
<li>
<b>Metropolitan regions</b>, if more than half of the population live in a FUA. Metropolitan regions are further classified into: <b>metropolitan large</b>, if more than half of the population live in a (large) FUA of at least 1.5 million inhabitants; and <b>metropolitan midsize</b>, if more than half of the population live in a (midsize) FUA of at 250 000 to 1.5 million inhabitants.
</li>
<li>
<b>Non-metropolitan regions</b>, if less than half of the population live in a midsize/large FUA. These regions are further classified according to their level of access to FUAs of different sizes: <b>near a midsize/large FUA</b>&nbsp;if more than half of the population live within a 60-minute drive from a midsize/large FUA (of more than 250 000 inhabitants) or if the TL3 region contains more than 80% of the area of a midsize/large FUA; <b>near a small FUA</b>&nbsp;if the region does not have access to a midsize/large FUA and at least half of its population have access to a small FUA (i.e.&nbsp;between 50 000 and 250 000 inhabitants) within a 60-minute drive, or contains 80% of the area of a small FUA; and <b>remote</b>, otherwise.
</li>
</ul>
<p></p>
<p style="padding-left:10px;padding-right:10px;font-size:9.0pt;">
Disclaimer: <a href="https://oecdcode.org/disclaimers/territories.html" target="_blank"><i style="color:#0d6efd">https://oecdcode.org/disclaimers/territories.html</i></a>
</p>
</td>
</tr>

</tbody></table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tl3-aut.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Austria</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tl2-can.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">Canada</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>